### ISSUE TITLE
C++11 update?

### ISSUE THREAD

**Issue by ghost** [arekbee/CppWorkshop#1]
How about updating the workshop to C++11 and further? ;)

**Comment by ghost** [comment]
If you need some input - I can help you.

**Comment by arekbee** [comment]
Hi artopantone (ar2),
I  would be happy to use your exp. in c++ :)
I'm  doing this course to systematize knowledge and get to know new features xx11 and above, 
so work with c++11 will be included.

**Comment by ghost** [comment]
:+1: sounds like a good plan. Don't hesitate to ask. Best!
